### ISSUE TITLE
edge case

### ISSUE THREAD

**Issue by theelous3** [clement-daubrenet/algorithms#1]
```python
>>> def extract_max_recursion(a_string):
...     """
...     Here, +1 for an open parenthesis, -1 for a closing one.
...     We keep a track of the value in a counter, the maximum value taken
...     by this counter is the maximum recursion level.
...     """
...     counter = 0
...     maximum = 0
...     for character in a_string:
...         if character == ')':
...             counter -= 1
...             if counter > maximum:
...                 maximum = counter
...         elif character == '(':
...             counter += 1
...             if counter > maximum:
...                 maximum = counter
...     return maximum
... 
>>> extract_max_recursion('((((')
4

```

The above should be 0

If we could have memory efficient iterator reversing we could make a v nice and complete checker. Sadly that's not the case atm. Might go look in to writing one to solve this in a fun way. It would only solve cases where the given item is a sequence though. Wouldn't work when getting the nesting from an iterator to begin with. If we presume that the initial string is ok to hold in memory then it shoud be fine. Maybe a new version of islice is needed too. Idk. Rambling. Hope all is well :)

**Comment by clement-daubrenet** [comment]
Haha fair enough mister.
Thought about those but life is too short for edge cases.

**Comment by theelous3** [comment]
Go to bed you maniac!
